name: Publish Extension

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Increase package.json version
        if: startsWith(github.event.pull_request.title, 'major')
        run: npm version major
      - if: startsWith(github.event.pull_request.title, 'minor')
        run: npm version minor
      - if: startsWith(github.event.pull_request.title, 'bug')
        run: npm version patch
      - name: Build extension
        run: bun build
      - name: Push extension to marketplace
        run: vsce publish