on:
  push:
    branches:
      - master
name: Deploy Extension
jobs:
  version_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print things
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }}  event. ${{github.base_ref}}"

      - name: Increase package.json version
        if: startsWith(github.base_ref, 'major')
        run: npm version major
      - if: startsWith(github.base_ref, 'minor')
        run: npm version minor
      - if: startsWith(github.base_ref, 'bug')
        run: npm version patch

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}