name: Publish Extension

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: lannonbr/vsce-action@3.0.0
        with:
            args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCODE_PAT }}
      - name: Install dependencies
        run: bun install
      - name: Increase package.json version
        if: startsWith(github.event.pull_request.title, 'major')
        run: npm version major
      - if: startsWith(github.event.pull_request.title, 'minor')
        run: npm version minor
      - if: startsWith(github.event.pull_request.title, 'bug')
        run: npm version patch
      - name: Build extension
        run: vsce package
      - name: Push extension to marketplace
        run: vsce publish